export const qk = {
  config: ['config'] as const,
  nearby: (lat: number, lng: number, radiusKm: number, q: string) => ['nearby', lat, lng, radiusKm, q] as const,
  restaurant: (id: string) => ['restaurant', id] as const,
  menu: (id: string) => ['menu', id] as const,
  party: (id: string) => ['party', id] as const,
  partyDetail: (id: string) => ['party', id, 'detail'] as const,
  members: (id: string) => ['party', id, 'members'] as const,
  votes: (id: string) => ['party', id, 'votes'] as const,
  items: (id: string) => ['party', id, 'items'] as const,
  payments: (id: string) => ['party', id, 'payments'] as const,
  summary: (id: string) => ['party', id, 'summary'] as const,
  paymentQR: (paymentId: string) => ['paymentQR', paymentId] as const,
  myParties: (userId: string) => ['myParties', userId] as const,
  history: (userId: string) => ['history', userId] as const,
  myStats: (userId: string) => ['history', userId, 'stats'] as const,
  reorder: (partyId: string) => ['party', partyId, 'reorder'] as const,
  payout: (userId: string) => ['payout', userId] as const,
  authMethods: ['authMethods'] as const,
  admin: {
    all: ['admin'] as const,
    stats: ['admin', 'stats'] as const,
    restaurants: ['admin', 'restaurants'] as const,
    restaurant: (id: string) => ['admin', 'restaurant', id] as const,
    menu: (id: string) => ['admin', 'menu', id] as const,
    parties: (status: string, page: number) => ['admin', 'parties', status, page] as const,
    party: (id: string) => ['admin', 'party', id] as const,
    users: (q: string, role: string) => ['admin', 'users', q, role] as const,
    syncStatus: ['admin', 'sync', 'status'] as const,
    syncRuns: (page: number) => ['admin', 'sync', 'runs', page] as const,
    syncRun: (id: string) => ['admin', 'sync', 'run', id] as const,
    syncSources: ['admin', 'sync', 'sources'] as const,
    settings: ['admin', 'settings'] as const,
  },
}
